version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=containers-us-west-XX.railway.app
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=pools
      - DB_POSTGRESDB_USER=lucasadmin
      - DB_POSTGRESDB_PASSWORD=a6da6%82#sS*!DA0
      - N8N_REDIS_HOST=redis
      - WEBHOOK_URL=postgres://lucasadmin:a6da6%82#sS*!DA0@containers-us-west-XX.railway.app:5432/pools

    depends_on:
      - postgres
      - redis

  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=pools
      - POSTGRESQL_USERNAME=lucasadmin
      - POSTGRESQL_PASSWORD=a6da6%82#sS*!DA0
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=a6da6%82#sS*!DA0
    volumes:
      - redis_data:/bitnami/redis

volumes:
  postgres_data:
  redis_data:
